# Generated by Django 2.2.9 on 2020-09-27 03:22

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=core.models.get_file_path, verbose_name='Foto'),
        ),
    ]
